### ISSUE TITLE
Wrong default behaviour of `load_db` if multiple tables with same `table_name_pattern` exist in CDM instance

### ISSUE THREAD

**Issue by LindaNab** [UMC-Utrecht-RWE/T2-DataManagementModel#25]
When using the function `load_db` using dummy CDM data with more than one csv with e.g. MEDICINES data (in my case: `MEDICINES_3.csv` and `MEDICINES_PAXLOVID.csv`), the csv that is loaded secondly needs to contain the same columns as the first csv. In my use case, this wasn't true, and as a consequence the message was printed to the console, subsequently resulting in an error:

```
[1] "[load_db]: Loading: MEDICINES_3.csv 1/2"
[1] "[load_db]: Loading: MEDICINES_PAXLOVID.csv 2/2"
[1] "[load_db]: The following columns are missing in the input: y"
Error: near "ADD": syntax error
```
The message is a consequence of a check done [here](https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel/blob/daae65ad025791af414d5f01e888b32944a1e05a/R/load_db.R#L68-L79). Subsequently, `load_db` [tries to alter the table by adding in the missing columns](https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel/blob/daae65ad025791af414d5f01e888b32944a1e05a/R/load_db.R#L81-L83), resulting in the error as shown above.

I think the desired behaviour here is to:
- Change the message to something more informative like: "The following columns do not exist in <<MEDICINES_PAXLOVID.csv>> but do exist in (one of the) other tables containing MEDICINES data: <<insert columns>>. The following columns do exist in <<MEDICINES_PAXLOVID.csv>> and did not exist in (one of the) other tables containing MEDICINES data yet: <<insert columns>>. Columns <<xxxx>> and <<yyyy>> are added to table MEDICINES.
And subsequently add all the columns to the MEDICINES table in the db:
- The columns in `MEDICINES_3.csv` and NOT in `MEDICINES_PAXLOVID.csv` AND 
- The columns in `MEDICINES_PAXLOVID.csv` and NOT in `MEDICINES_3.csv`
In this way the two tables can be appended and the non-overlapping columns `NA`.

**Comment by acidroyo** [comment]
Thank you very much @LindaNab  for the issue!
