### ISSUE TITLE
load_db() error 

### ISSUE THREAD

**Issue by YMao-UMCU** [UMC-Utrecht-RWE/T2-DataManagementModel#33]
I installed the newest version of T2.DMM package, and adapted set_database in paxlovid project ([commit](https://github.com/UMC-Utrecht-RWE/Paxlovid-1047/pull/164/commits/8c1b7483e002760b8957529d75c775dfabb1aa38)), and this error occurred that seemed to be a syntax error at the duckdb query. Error message:

```
> load_db(
+   db_connection = d2_db_conn, csv_path_dir = dir_data,
+   cdm_metadata = cdm_metadata, cdm_tables_names = cdm_tables_names
+ )
[1] "[load_db]: Loading: PERSONS_PX_RENHEP.csv 1/2"
[1] "[load_db]: Loading: PERSONS.csv 2/2"
[1] "[load_db]: The following columns are in PERSONS.csv and not in the previously loaded PERSONS csvs: dap"
[1] "[load_db]: Adding column: dap to table PERSONS in the database"
Error: {"exception_type":"Parser","exception_message":"syntax error at or near \";\"","position":"35","error_subtype":"SYNTAX_ERROR"}
> 
```

Tracing the error it appeared at line 69 in the load_db function

```
  p <- DBI::dbSendStatement(db_connection, 
              paste0("ALTER TABLE ", table_name_pattern, 
                " ADD COLUMN ", new_column, " ;"))
            DBI::dbClearResult(p)
```

Any clue? @acidroyo 

UPDATE
I did a little search on duckdb ALTER TABLE, it seems the query requires the column type definition. Change it to 
```
  p <- DBI::dbSendStatement(db_connection, 
              paste0("ALTER TABLE ", table_name_pattern, 
                " ADD COLUMN ", new_column, " VARCHAR;"))
            DBI::dbClearResult(p)
```
made it work. Can you double check? @acidroyo

**Comment by acidroyo** [comment]
@YMao-UMCU Line 69 does not match to the line 69 of the last version of the code; https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel/blob/a517b83b23e865445d5ff1c30fdf869420b42498/R/load_db.R#L69C8-L72C28

**Comment by YMao-UMCU** [comment]
solved!
