### ISSUE TITLE
create_unique_id() error

### ISSUE THREAD

**Issue by YMao-UMCU** [UMC-Utrecht-RWE/T2-DataManagementModel#34]
Same back ground as #33 

An error appeared at line 24 in create_unique_id

```
     rs <- DBI::dbSendStatement(db_connection, paste0("ALTER TABLE ", 
        table, " RENAME TO OLD_", table, ";"), n = -1)
```

and the error message
```
Error: rapi_execute: Failed to run query
Error: Catalog Error: Could not rename "PERSONS" to "OLD_PERSONS": another entry with this name already exists!
```

**Comment by acidroyo** [comment]
hello @YMao-UMCU the code it's giving you error was deleted on a previous version: https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel/commit/1334c8a00f5fe8cc2d9fa9945375ff5b83c88bf6 
Check that you have the last version installed

**Comment by YMao-UMCU** [comment]
yes it's solved. Thanks!
